<?php
/**
 * GiftCardAccountGiftCardAccountManagementV1Api
 * PHP version 5
 *
 * @category Class
 * @package  Krak\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Commerce for B2B
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Krak\MagentoApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Krak\MagentoApiClient\ApiException;
use Krak\MagentoApiClient\Configuration;
use Krak\MagentoApiClient\HeaderSelector;
use Krak\MagentoApiClient\ObjectSerializer;

/**
 * GiftCardAccountGiftCardAccountManagementV1Api Class Doc Comment
 *
 * @category Class
 * @package  Krak\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GiftCardAccountGiftCardAccountManagementV1Api
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1CheckGiftCardGet
     *
     * @param  string $giftCardCode giftCardCode (required)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return float
     */
    public function giftCardAccountGiftCardAccountManagementV1CheckGiftCardGet($giftCardCode)
    {
        list($response) = $this->giftCardAccountGiftCardAccountManagementV1CheckGiftCardGetWithHttpInfo($giftCardCode);
        return $response;
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1CheckGiftCardGetWithHttpInfo
     *
     * @param  string $giftCardCode (required)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of float, HTTP status code, HTTP response headers (array of strings)
     */
    public function giftCardAccountGiftCardAccountManagementV1CheckGiftCardGetWithHttpInfo($giftCardCode)
    {
        $returnType = 'float';
        $request = $this->giftCardAccountGiftCardAccountManagementV1CheckGiftCardGetRequest($giftCardCode);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'float',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1CheckGiftCardGetAsync
     *
     * 
     *
     * @param  string $giftCardCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1CheckGiftCardGetAsync($giftCardCode)
    {
        return $this->giftCardAccountGiftCardAccountManagementV1CheckGiftCardGetAsyncWithHttpInfo($giftCardCode)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1CheckGiftCardGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $giftCardCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1CheckGiftCardGetAsyncWithHttpInfo($giftCardCode)
    {
        $returnType = 'float';
        $request = $this->giftCardAccountGiftCardAccountManagementV1CheckGiftCardGetRequest($giftCardCode);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'giftCardAccountGiftCardAccountManagementV1CheckGiftCardGet'
     *
     * @param  string $giftCardCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function giftCardAccountGiftCardAccountManagementV1CheckGiftCardGetRequest($giftCardCode)
    {
        // verify the required parameter 'giftCardCode' is set
        if ($giftCardCode === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $giftCardCode when calling giftCardAccountGiftCardAccountManagementV1CheckGiftCardGet'
            );
        }

        $resourcePath = '/V1/carts/mine/checkGiftCard/{giftCardCode}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($giftCardCode !== null) {
            $resourcePath = str_replace(
                '{' . 'giftCardCode' . '}',
                ObjectSerializer::toPathValue($giftCardCode),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete
     *
     * @param  int $cartId cartId (required)
     * @param  string $giftCardCode giftCardCode (required)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return bool
     */
    public function giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete($cartId, $giftCardCode)
    {
        list($response) = $this->giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDeleteWithHttpInfo($cartId, $giftCardCode);
        return $response;
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDeleteWithHttpInfo
     *
     * @param  int $cartId (required)
     * @param  string $giftCardCode (required)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of bool, HTTP status code, HTTP response headers (array of strings)
     */
    public function giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDeleteWithHttpInfo($cartId, $giftCardCode)
    {
        $returnType = 'bool';
        $request = $this->giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDeleteRequest($cartId, $giftCardCode);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'bool',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDeleteAsync
     *
     * 
     *
     * @param  int $cartId (required)
     * @param  string $giftCardCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDeleteAsync($cartId, $giftCardCode)
    {
        return $this->giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDeleteAsyncWithHttpInfo($cartId, $giftCardCode)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDeleteAsyncWithHttpInfo
     *
     * 
     *
     * @param  int $cartId (required)
     * @param  string $giftCardCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDeleteAsyncWithHttpInfo($cartId, $giftCardCode)
    {
        $returnType = 'bool';
        $request = $this->giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDeleteRequest($cartId, $giftCardCode);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete'
     *
     * @param  int $cartId (required)
     * @param  string $giftCardCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDeleteRequest($cartId, $giftCardCode)
    {
        // verify the required parameter 'cartId' is set
        if ($cartId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cartId when calling giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete'
            );
        }
        // verify the required parameter 'giftCardCode' is set
        if ($giftCardCode === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $giftCardCode when calling giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete'
            );
        }

        $resourcePath = '/V1/carts/{cartId}/giftCards/{giftCardCode}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($cartId !== null) {
            $resourcePath = str_replace(
                '{' . 'cartId' . '}',
                ObjectSerializer::toPathValue($cartId),
                $resourcePath
            );
        }
        // path params
        if ($giftCardCode !== null) {
            $resourcePath = str_replace(
                '{' . 'giftCardCode' . '}',
                ObjectSerializer::toPathValue($giftCardCode),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0
     *
     * @param  string $giftCardCode giftCardCode (required)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return bool
     */
    public function giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0($giftCardCode)
    {
        list($response) = $this->giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0WithHttpInfo($giftCardCode);
        return $response;
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0WithHttpInfo
     *
     * @param  string $giftCardCode (required)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of bool, HTTP status code, HTTP response headers (array of strings)
     */
    public function giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0WithHttpInfo($giftCardCode)
    {
        $returnType = 'bool';
        $request = $this->giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0Request($giftCardCode);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'bool',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0Async
     *
     * 
     *
     * @param  string $giftCardCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0Async($giftCardCode)
    {
        return $this->giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0AsyncWithHttpInfo($giftCardCode)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0AsyncWithHttpInfo
     *
     * 
     *
     * @param  string $giftCardCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0AsyncWithHttpInfo($giftCardCode)
    {
        $returnType = 'bool';
        $request = $this->giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0Request($giftCardCode);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0'
     *
     * @param  string $giftCardCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0Request($giftCardCode)
    {
        // verify the required parameter 'giftCardCode' is set
        if ($giftCardCode === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $giftCardCode when calling giftCardAccountGiftCardAccountManagementV1DeleteByQuoteIdDelete_0'
            );
        }

        $resourcePath = '/V1/carts/mine/giftCards/{giftCardCode}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($giftCardCode !== null) {
            $resourcePath = str_replace(
                '{' . 'giftCardCode' . '}',
                ObjectSerializer::toPathValue($giftCardCode),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGet
     *
     * @param  int $quoteId quoteId (required)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Krak\MagentoApiClient\Model\GiftCardAccountDataGiftCardAccountInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGet($quoteId)
    {
        list($response) = $this->giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGetWithHttpInfo($quoteId);
        return $response;
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGetWithHttpInfo
     *
     * @param  int $quoteId (required)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Krak\MagentoApiClient\Model\GiftCardAccountDataGiftCardAccountInterface, HTTP status code, HTTP response headers (array of strings)
     */
    public function giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGetWithHttpInfo($quoteId)
    {
        $returnType = '\Krak\MagentoApiClient\Model\GiftCardAccountDataGiftCardAccountInterface';
        $request = $this->giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGetRequest($quoteId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\GiftCardAccountDataGiftCardAccountInterface',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGetAsync
     *
     * 
     *
     * @param  int $quoteId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGetAsync($quoteId)
    {
        return $this->giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGetAsyncWithHttpInfo($quoteId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  int $quoteId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGetAsyncWithHttpInfo($quoteId)
    {
        $returnType = '\Krak\MagentoApiClient\Model\GiftCardAccountDataGiftCardAccountInterface';
        $request = $this->giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGetRequest($quoteId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGet'
     *
     * @param  int $quoteId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGetRequest($quoteId)
    {
        // verify the required parameter 'quoteId' is set
        if ($quoteId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $quoteId when calling giftCardAccountGiftCardAccountManagementV1GetListByQuoteIdGet'
            );
        }

        $resourcePath = '/V1/carts/{quoteId}/giftCards';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($quoteId !== null) {
            $resourcePath = str_replace(
                '{' . 'quoteId' . '}',
                ObjectSerializer::toPathValue($quoteId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPost
     *
     * @param  \Krak\MagentoApiClient\Model\GiftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody (optional)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return bool
     */
    public function giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPost($giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody = null)
    {
        list($response) = $this->giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostWithHttpInfo($giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody);
        return $response;
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostWithHttpInfo
     *
     * @param  \Krak\MagentoApiClient\Model\GiftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody (optional)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of bool, HTTP status code, HTTP response headers (array of strings)
     */
    public function giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostWithHttpInfo($giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody = null)
    {
        $returnType = 'bool';
        $request = $this->giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostRequest($giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'bool',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostAsync
     *
     * 
     *
     * @param  \Krak\MagentoApiClient\Model\GiftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostAsync($giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody = null)
    {
        return $this->giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostAsyncWithHttpInfo($giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Krak\MagentoApiClient\Model\GiftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostAsyncWithHttpInfo($giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody = null)
    {
        $returnType = 'bool';
        $request = $this->giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostRequest($giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPost'
     *
     * @param  \Krak\MagentoApiClient\Model\GiftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostRequest($giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody = null)
    {

        $resourcePath = '/V1/carts/mine/giftCards';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody)) {
            $_tempBody = $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPostBody;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPut
     *
     * @param  int $cartId cartId (required)
     * @param  \Krak\MagentoApiClient\Model\GiftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody (optional)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return bool
     */
    public function giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPut($cartId, $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody = null)
    {
        list($response) = $this->giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutWithHttpInfo($cartId, $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody);
        return $response;
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutWithHttpInfo
     *
     * @param  int $cartId (required)
     * @param  \Krak\MagentoApiClient\Model\GiftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody (optional)
     *
     * @throws \Krak\MagentoApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of bool, HTTP status code, HTTP response headers (array of strings)
     */
    public function giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutWithHttpInfo($cartId, $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody = null)
    {
        $returnType = 'bool';
        $request = $this->giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutRequest($cartId, $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'bool',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Krak\MagentoApiClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutAsync
     *
     * 
     *
     * @param  int $cartId (required)
     * @param  \Krak\MagentoApiClient\Model\GiftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutAsync($cartId, $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody = null)
    {
        return $this->giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutAsyncWithHttpInfo($cartId, $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutAsyncWithHttpInfo
     *
     * 
     *
     * @param  int $cartId (required)
     * @param  \Krak\MagentoApiClient\Model\GiftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutAsyncWithHttpInfo($cartId, $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody = null)
    {
        $returnType = 'bool';
        $request = $this->giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutRequest($cartId, $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPut'
     *
     * @param  int $cartId (required)
     * @param  \Krak\MagentoApiClient\Model\GiftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutRequest($cartId, $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody = null)
    {
        // verify the required parameter 'cartId' is set
        if ($cartId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cartId when calling giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPut'
            );
        }

        $resourcePath = '/V1/carts/{cartId}/giftCards';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($cartId !== null) {
            $resourcePath = str_replace(
                '{' . 'cartId' . '}',
                ObjectSerializer::toPathValue($cartId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody)) {
            $_tempBody = $giftCardAccountGiftCardAccountManagementV1SaveByQuoteIdPutBody;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
