<?php
/**
 * SalesDataOrderExtensionInterface
 *
 * PHP version 5
 *
 * @category Class
 * @package  Krak\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Commerce for B2B
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Krak\MagentoApiClient\Model;

use \ArrayAccess;
use \Krak\MagentoApiClient\ObjectSerializer;

/**
 * SalesDataOrderExtensionInterface Class Doc Comment
 *
 * @category Class
 * @description ExtensionInterface class for @see \\Magento\\Sales\\Api\\Data\\OrderInterface
 * @package  Krak\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SalesDataOrderExtensionInterface implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'sales-data-order-extension-interface';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'shippingAssignments' => '\Krak\MagentoApiClient\Model\SalesDataShippingAssignmentInterface[]',
        'appliedTaxes' => '\Krak\MagentoApiClient\Model\TaxDataOrderTaxDetailsAppliedTaxInterface[]',
        'itemAppliedTaxes' => '\Krak\MagentoApiClient\Model\TaxDataOrderTaxDetailsItemInterface[]',
        'convertingFromQuote' => 'bool',
        'companyOrderAttributes' => '\Krak\MagentoApiClient\Model\CompanyDataCompanyOrderInterface',
        'baseCustomerBalanceAmount' => 'float',
        'customerBalanceAmount' => 'float',
        'baseCustomerBalanceInvoiced' => 'float',
        'customerBalanceInvoiced' => 'float',
        'baseCustomerBalanceRefunded' => 'float',
        'customerBalanceRefunded' => 'float',
        'baseCustomerBalanceTotalRefunded' => 'float',
        'customerBalanceTotalRefunded' => 'float',
        'giftCards' => '\Krak\MagentoApiClient\Model\GiftCardAccountDataGiftCardInterface[]',
        'baseGiftCardsAmount' => 'float',
        'giftCardsAmount' => 'float',
        'baseGiftCardsInvoiced' => 'float',
        'giftCardsInvoiced' => 'float',
        'baseGiftCardsRefunded' => 'float',
        'giftCardsRefunded' => 'float',
        'giftMessage' => '\Krak\MagentoApiClient\Model\GiftMessageDataMessageInterface',
        'gwId' => 'string',
        'gwAllowGiftReceipt' => 'string',
        'gwAddCard' => 'string',
        'gwBasePrice' => 'string',
        'gwPrice' => 'string',
        'gwItemsBasePrice' => 'string',
        'gwItemsPrice' => 'string',
        'gwCardBasePrice' => 'string',
        'gwCardPrice' => 'string',
        'gwBaseTaxAmount' => 'string',
        'gwTaxAmount' => 'string',
        'gwItemsBaseTaxAmount' => 'string',
        'gwItemsTaxAmount' => 'string',
        'gwCardBaseTaxAmount' => 'string',
        'gwCardTaxAmount' => 'string',
        'gwBasePriceInclTax' => 'string',
        'gwPriceInclTax' => 'string',
        'gwItemsBasePriceInclTax' => 'string',
        'gwItemsPriceInclTax' => 'string',
        'gwCardBasePriceInclTax' => 'string',
        'gwCardPriceInclTax' => 'string',
        'gwBasePriceInvoiced' => 'string',
        'gwPriceInvoiced' => 'string',
        'gwItemsBasePriceInvoiced' => 'string',
        'gwItemsPriceInvoiced' => 'string',
        'gwCardBasePriceInvoiced' => 'string',
        'gwCardPriceInvoiced' => 'string',
        'gwBaseTaxAmountInvoiced' => 'string',
        'gwTaxAmountInvoiced' => 'string',
        'gwItemsBaseTaxInvoiced' => 'string',
        'gwItemsTaxInvoiced' => 'string',
        'gwCardBaseTaxInvoiced' => 'string',
        'gwCardTaxInvoiced' => 'string',
        'gwBasePriceRefunded' => 'string',
        'gwPriceRefunded' => 'string',
        'gwItemsBasePriceRefunded' => 'string',
        'gwItemsPriceRefunded' => 'string',
        'gwCardBasePriceRefunded' => 'string',
        'gwCardPriceRefunded' => 'string',
        'gwBaseTaxAmountRefunded' => 'string',
        'gwTaxAmountRefunded' => 'string',
        'gwItemsBaseTaxRefunded' => 'string',
        'gwItemsTaxRefunded' => 'string',
        'gwCardBaseTaxRefunded' => 'string',
        'gwCardTaxRefunded' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'shippingAssignments' => null,
        'appliedTaxes' => null,
        'itemAppliedTaxes' => null,
        'convertingFromQuote' => null,
        'companyOrderAttributes' => null,
        'baseCustomerBalanceAmount' => null,
        'customerBalanceAmount' => null,
        'baseCustomerBalanceInvoiced' => null,
        'customerBalanceInvoiced' => null,
        'baseCustomerBalanceRefunded' => null,
        'customerBalanceRefunded' => null,
        'baseCustomerBalanceTotalRefunded' => null,
        'customerBalanceTotalRefunded' => null,
        'giftCards' => null,
        'baseGiftCardsAmount' => null,
        'giftCardsAmount' => null,
        'baseGiftCardsInvoiced' => null,
        'giftCardsInvoiced' => null,
        'baseGiftCardsRefunded' => null,
        'giftCardsRefunded' => null,
        'giftMessage' => null,
        'gwId' => null,
        'gwAllowGiftReceipt' => null,
        'gwAddCard' => null,
        'gwBasePrice' => null,
        'gwPrice' => null,
        'gwItemsBasePrice' => null,
        'gwItemsPrice' => null,
        'gwCardBasePrice' => null,
        'gwCardPrice' => null,
        'gwBaseTaxAmount' => null,
        'gwTaxAmount' => null,
        'gwItemsBaseTaxAmount' => null,
        'gwItemsTaxAmount' => null,
        'gwCardBaseTaxAmount' => null,
        'gwCardTaxAmount' => null,
        'gwBasePriceInclTax' => null,
        'gwPriceInclTax' => null,
        'gwItemsBasePriceInclTax' => null,
        'gwItemsPriceInclTax' => null,
        'gwCardBasePriceInclTax' => null,
        'gwCardPriceInclTax' => null,
        'gwBasePriceInvoiced' => null,
        'gwPriceInvoiced' => null,
        'gwItemsBasePriceInvoiced' => null,
        'gwItemsPriceInvoiced' => null,
        'gwCardBasePriceInvoiced' => null,
        'gwCardPriceInvoiced' => null,
        'gwBaseTaxAmountInvoiced' => null,
        'gwTaxAmountInvoiced' => null,
        'gwItemsBaseTaxInvoiced' => null,
        'gwItemsTaxInvoiced' => null,
        'gwCardBaseTaxInvoiced' => null,
        'gwCardTaxInvoiced' => null,
        'gwBasePriceRefunded' => null,
        'gwPriceRefunded' => null,
        'gwItemsBasePriceRefunded' => null,
        'gwItemsPriceRefunded' => null,
        'gwCardBasePriceRefunded' => null,
        'gwCardPriceRefunded' => null,
        'gwBaseTaxAmountRefunded' => null,
        'gwTaxAmountRefunded' => null,
        'gwItemsBaseTaxRefunded' => null,
        'gwItemsTaxRefunded' => null,
        'gwCardBaseTaxRefunded' => null,
        'gwCardTaxRefunded' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shippingAssignments' => 'shipping_assignments',
        'appliedTaxes' => 'applied_taxes',
        'itemAppliedTaxes' => 'item_applied_taxes',
        'convertingFromQuote' => 'converting_from_quote',
        'companyOrderAttributes' => 'company_order_attributes',
        'baseCustomerBalanceAmount' => 'base_customer_balance_amount',
        'customerBalanceAmount' => 'customer_balance_amount',
        'baseCustomerBalanceInvoiced' => 'base_customer_balance_invoiced',
        'customerBalanceInvoiced' => 'customer_balance_invoiced',
        'baseCustomerBalanceRefunded' => 'base_customer_balance_refunded',
        'customerBalanceRefunded' => 'customer_balance_refunded',
        'baseCustomerBalanceTotalRefunded' => 'base_customer_balance_total_refunded',
        'customerBalanceTotalRefunded' => 'customer_balance_total_refunded',
        'giftCards' => 'gift_cards',
        'baseGiftCardsAmount' => 'base_gift_cards_amount',
        'giftCardsAmount' => 'gift_cards_amount',
        'baseGiftCardsInvoiced' => 'base_gift_cards_invoiced',
        'giftCardsInvoiced' => 'gift_cards_invoiced',
        'baseGiftCardsRefunded' => 'base_gift_cards_refunded',
        'giftCardsRefunded' => 'gift_cards_refunded',
        'giftMessage' => 'gift_message',
        'gwId' => 'gw_id',
        'gwAllowGiftReceipt' => 'gw_allow_gift_receipt',
        'gwAddCard' => 'gw_add_card',
        'gwBasePrice' => 'gw_base_price',
        'gwPrice' => 'gw_price',
        'gwItemsBasePrice' => 'gw_items_base_price',
        'gwItemsPrice' => 'gw_items_price',
        'gwCardBasePrice' => 'gw_card_base_price',
        'gwCardPrice' => 'gw_card_price',
        'gwBaseTaxAmount' => 'gw_base_tax_amount',
        'gwTaxAmount' => 'gw_tax_amount',
        'gwItemsBaseTaxAmount' => 'gw_items_base_tax_amount',
        'gwItemsTaxAmount' => 'gw_items_tax_amount',
        'gwCardBaseTaxAmount' => 'gw_card_base_tax_amount',
        'gwCardTaxAmount' => 'gw_card_tax_amount',
        'gwBasePriceInclTax' => 'gw_base_price_incl_tax',
        'gwPriceInclTax' => 'gw_price_incl_tax',
        'gwItemsBasePriceInclTax' => 'gw_items_base_price_incl_tax',
        'gwItemsPriceInclTax' => 'gw_items_price_incl_tax',
        'gwCardBasePriceInclTax' => 'gw_card_base_price_incl_tax',
        'gwCardPriceInclTax' => 'gw_card_price_incl_tax',
        'gwBasePriceInvoiced' => 'gw_base_price_invoiced',
        'gwPriceInvoiced' => 'gw_price_invoiced',
        'gwItemsBasePriceInvoiced' => 'gw_items_base_price_invoiced',
        'gwItemsPriceInvoiced' => 'gw_items_price_invoiced',
        'gwCardBasePriceInvoiced' => 'gw_card_base_price_invoiced',
        'gwCardPriceInvoiced' => 'gw_card_price_invoiced',
        'gwBaseTaxAmountInvoiced' => 'gw_base_tax_amount_invoiced',
        'gwTaxAmountInvoiced' => 'gw_tax_amount_invoiced',
        'gwItemsBaseTaxInvoiced' => 'gw_items_base_tax_invoiced',
        'gwItemsTaxInvoiced' => 'gw_items_tax_invoiced',
        'gwCardBaseTaxInvoiced' => 'gw_card_base_tax_invoiced',
        'gwCardTaxInvoiced' => 'gw_card_tax_invoiced',
        'gwBasePriceRefunded' => 'gw_base_price_refunded',
        'gwPriceRefunded' => 'gw_price_refunded',
        'gwItemsBasePriceRefunded' => 'gw_items_base_price_refunded',
        'gwItemsPriceRefunded' => 'gw_items_price_refunded',
        'gwCardBasePriceRefunded' => 'gw_card_base_price_refunded',
        'gwCardPriceRefunded' => 'gw_card_price_refunded',
        'gwBaseTaxAmountRefunded' => 'gw_base_tax_amount_refunded',
        'gwTaxAmountRefunded' => 'gw_tax_amount_refunded',
        'gwItemsBaseTaxRefunded' => 'gw_items_base_tax_refunded',
        'gwItemsTaxRefunded' => 'gw_items_tax_refunded',
        'gwCardBaseTaxRefunded' => 'gw_card_base_tax_refunded',
        'gwCardTaxRefunded' => 'gw_card_tax_refunded'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shippingAssignments' => 'setShippingAssignments',
        'appliedTaxes' => 'setAppliedTaxes',
        'itemAppliedTaxes' => 'setItemAppliedTaxes',
        'convertingFromQuote' => 'setConvertingFromQuote',
        'companyOrderAttributes' => 'setCompanyOrderAttributes',
        'baseCustomerBalanceAmount' => 'setBaseCustomerBalanceAmount',
        'customerBalanceAmount' => 'setCustomerBalanceAmount',
        'baseCustomerBalanceInvoiced' => 'setBaseCustomerBalanceInvoiced',
        'customerBalanceInvoiced' => 'setCustomerBalanceInvoiced',
        'baseCustomerBalanceRefunded' => 'setBaseCustomerBalanceRefunded',
        'customerBalanceRefunded' => 'setCustomerBalanceRefunded',
        'baseCustomerBalanceTotalRefunded' => 'setBaseCustomerBalanceTotalRefunded',
        'customerBalanceTotalRefunded' => 'setCustomerBalanceTotalRefunded',
        'giftCards' => 'setGiftCards',
        'baseGiftCardsAmount' => 'setBaseGiftCardsAmount',
        'giftCardsAmount' => 'setGiftCardsAmount',
        'baseGiftCardsInvoiced' => 'setBaseGiftCardsInvoiced',
        'giftCardsInvoiced' => 'setGiftCardsInvoiced',
        'baseGiftCardsRefunded' => 'setBaseGiftCardsRefunded',
        'giftCardsRefunded' => 'setGiftCardsRefunded',
        'giftMessage' => 'setGiftMessage',
        'gwId' => 'setGwId',
        'gwAllowGiftReceipt' => 'setGwAllowGiftReceipt',
        'gwAddCard' => 'setGwAddCard',
        'gwBasePrice' => 'setGwBasePrice',
        'gwPrice' => 'setGwPrice',
        'gwItemsBasePrice' => 'setGwItemsBasePrice',
        'gwItemsPrice' => 'setGwItemsPrice',
        'gwCardBasePrice' => 'setGwCardBasePrice',
        'gwCardPrice' => 'setGwCardPrice',
        'gwBaseTaxAmount' => 'setGwBaseTaxAmount',
        'gwTaxAmount' => 'setGwTaxAmount',
        'gwItemsBaseTaxAmount' => 'setGwItemsBaseTaxAmount',
        'gwItemsTaxAmount' => 'setGwItemsTaxAmount',
        'gwCardBaseTaxAmount' => 'setGwCardBaseTaxAmount',
        'gwCardTaxAmount' => 'setGwCardTaxAmount',
        'gwBasePriceInclTax' => 'setGwBasePriceInclTax',
        'gwPriceInclTax' => 'setGwPriceInclTax',
        'gwItemsBasePriceInclTax' => 'setGwItemsBasePriceInclTax',
        'gwItemsPriceInclTax' => 'setGwItemsPriceInclTax',
        'gwCardBasePriceInclTax' => 'setGwCardBasePriceInclTax',
        'gwCardPriceInclTax' => 'setGwCardPriceInclTax',
        'gwBasePriceInvoiced' => 'setGwBasePriceInvoiced',
        'gwPriceInvoiced' => 'setGwPriceInvoiced',
        'gwItemsBasePriceInvoiced' => 'setGwItemsBasePriceInvoiced',
        'gwItemsPriceInvoiced' => 'setGwItemsPriceInvoiced',
        'gwCardBasePriceInvoiced' => 'setGwCardBasePriceInvoiced',
        'gwCardPriceInvoiced' => 'setGwCardPriceInvoiced',
        'gwBaseTaxAmountInvoiced' => 'setGwBaseTaxAmountInvoiced',
        'gwTaxAmountInvoiced' => 'setGwTaxAmountInvoiced',
        'gwItemsBaseTaxInvoiced' => 'setGwItemsBaseTaxInvoiced',
        'gwItemsTaxInvoiced' => 'setGwItemsTaxInvoiced',
        'gwCardBaseTaxInvoiced' => 'setGwCardBaseTaxInvoiced',
        'gwCardTaxInvoiced' => 'setGwCardTaxInvoiced',
        'gwBasePriceRefunded' => 'setGwBasePriceRefunded',
        'gwPriceRefunded' => 'setGwPriceRefunded',
        'gwItemsBasePriceRefunded' => 'setGwItemsBasePriceRefunded',
        'gwItemsPriceRefunded' => 'setGwItemsPriceRefunded',
        'gwCardBasePriceRefunded' => 'setGwCardBasePriceRefunded',
        'gwCardPriceRefunded' => 'setGwCardPriceRefunded',
        'gwBaseTaxAmountRefunded' => 'setGwBaseTaxAmountRefunded',
        'gwTaxAmountRefunded' => 'setGwTaxAmountRefunded',
        'gwItemsBaseTaxRefunded' => 'setGwItemsBaseTaxRefunded',
        'gwItemsTaxRefunded' => 'setGwItemsTaxRefunded',
        'gwCardBaseTaxRefunded' => 'setGwCardBaseTaxRefunded',
        'gwCardTaxRefunded' => 'setGwCardTaxRefunded'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shippingAssignments' => 'getShippingAssignments',
        'appliedTaxes' => 'getAppliedTaxes',
        'itemAppliedTaxes' => 'getItemAppliedTaxes',
        'convertingFromQuote' => 'getConvertingFromQuote',
        'companyOrderAttributes' => 'getCompanyOrderAttributes',
        'baseCustomerBalanceAmount' => 'getBaseCustomerBalanceAmount',
        'customerBalanceAmount' => 'getCustomerBalanceAmount',
        'baseCustomerBalanceInvoiced' => 'getBaseCustomerBalanceInvoiced',
        'customerBalanceInvoiced' => 'getCustomerBalanceInvoiced',
        'baseCustomerBalanceRefunded' => 'getBaseCustomerBalanceRefunded',
        'customerBalanceRefunded' => 'getCustomerBalanceRefunded',
        'baseCustomerBalanceTotalRefunded' => 'getBaseCustomerBalanceTotalRefunded',
        'customerBalanceTotalRefunded' => 'getCustomerBalanceTotalRefunded',
        'giftCards' => 'getGiftCards',
        'baseGiftCardsAmount' => 'getBaseGiftCardsAmount',
        'giftCardsAmount' => 'getGiftCardsAmount',
        'baseGiftCardsInvoiced' => 'getBaseGiftCardsInvoiced',
        'giftCardsInvoiced' => 'getGiftCardsInvoiced',
        'baseGiftCardsRefunded' => 'getBaseGiftCardsRefunded',
        'giftCardsRefunded' => 'getGiftCardsRefunded',
        'giftMessage' => 'getGiftMessage',
        'gwId' => 'getGwId',
        'gwAllowGiftReceipt' => 'getGwAllowGiftReceipt',
        'gwAddCard' => 'getGwAddCard',
        'gwBasePrice' => 'getGwBasePrice',
        'gwPrice' => 'getGwPrice',
        'gwItemsBasePrice' => 'getGwItemsBasePrice',
        'gwItemsPrice' => 'getGwItemsPrice',
        'gwCardBasePrice' => 'getGwCardBasePrice',
        'gwCardPrice' => 'getGwCardPrice',
        'gwBaseTaxAmount' => 'getGwBaseTaxAmount',
        'gwTaxAmount' => 'getGwTaxAmount',
        'gwItemsBaseTaxAmount' => 'getGwItemsBaseTaxAmount',
        'gwItemsTaxAmount' => 'getGwItemsTaxAmount',
        'gwCardBaseTaxAmount' => 'getGwCardBaseTaxAmount',
        'gwCardTaxAmount' => 'getGwCardTaxAmount',
        'gwBasePriceInclTax' => 'getGwBasePriceInclTax',
        'gwPriceInclTax' => 'getGwPriceInclTax',
        'gwItemsBasePriceInclTax' => 'getGwItemsBasePriceInclTax',
        'gwItemsPriceInclTax' => 'getGwItemsPriceInclTax',
        'gwCardBasePriceInclTax' => 'getGwCardBasePriceInclTax',
        'gwCardPriceInclTax' => 'getGwCardPriceInclTax',
        'gwBasePriceInvoiced' => 'getGwBasePriceInvoiced',
        'gwPriceInvoiced' => 'getGwPriceInvoiced',
        'gwItemsBasePriceInvoiced' => 'getGwItemsBasePriceInvoiced',
        'gwItemsPriceInvoiced' => 'getGwItemsPriceInvoiced',
        'gwCardBasePriceInvoiced' => 'getGwCardBasePriceInvoiced',
        'gwCardPriceInvoiced' => 'getGwCardPriceInvoiced',
        'gwBaseTaxAmountInvoiced' => 'getGwBaseTaxAmountInvoiced',
        'gwTaxAmountInvoiced' => 'getGwTaxAmountInvoiced',
        'gwItemsBaseTaxInvoiced' => 'getGwItemsBaseTaxInvoiced',
        'gwItemsTaxInvoiced' => 'getGwItemsTaxInvoiced',
        'gwCardBaseTaxInvoiced' => 'getGwCardBaseTaxInvoiced',
        'gwCardTaxInvoiced' => 'getGwCardTaxInvoiced',
        'gwBasePriceRefunded' => 'getGwBasePriceRefunded',
        'gwPriceRefunded' => 'getGwPriceRefunded',
        'gwItemsBasePriceRefunded' => 'getGwItemsBasePriceRefunded',
        'gwItemsPriceRefunded' => 'getGwItemsPriceRefunded',
        'gwCardBasePriceRefunded' => 'getGwCardBasePriceRefunded',
        'gwCardPriceRefunded' => 'getGwCardPriceRefunded',
        'gwBaseTaxAmountRefunded' => 'getGwBaseTaxAmountRefunded',
        'gwTaxAmountRefunded' => 'getGwTaxAmountRefunded',
        'gwItemsBaseTaxRefunded' => 'getGwItemsBaseTaxRefunded',
        'gwItemsTaxRefunded' => 'getGwItemsTaxRefunded',
        'gwCardBaseTaxRefunded' => 'getGwCardBaseTaxRefunded',
        'gwCardTaxRefunded' => 'getGwCardTaxRefunded'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shippingAssignments'] = isset($data['shippingAssignments']) ? $data['shippingAssignments'] : null;
        $this->container['appliedTaxes'] = isset($data['appliedTaxes']) ? $data['appliedTaxes'] : null;
        $this->container['itemAppliedTaxes'] = isset($data['itemAppliedTaxes']) ? $data['itemAppliedTaxes'] : null;
        $this->container['convertingFromQuote'] = isset($data['convertingFromQuote']) ? $data['convertingFromQuote'] : null;
        $this->container['companyOrderAttributes'] = isset($data['companyOrderAttributes']) ? $data['companyOrderAttributes'] : null;
        $this->container['baseCustomerBalanceAmount'] = isset($data['baseCustomerBalanceAmount']) ? $data['baseCustomerBalanceAmount'] : null;
        $this->container['customerBalanceAmount'] = isset($data['customerBalanceAmount']) ? $data['customerBalanceAmount'] : null;
        $this->container['baseCustomerBalanceInvoiced'] = isset($data['baseCustomerBalanceInvoiced']) ? $data['baseCustomerBalanceInvoiced'] : null;
        $this->container['customerBalanceInvoiced'] = isset($data['customerBalanceInvoiced']) ? $data['customerBalanceInvoiced'] : null;
        $this->container['baseCustomerBalanceRefunded'] = isset($data['baseCustomerBalanceRefunded']) ? $data['baseCustomerBalanceRefunded'] : null;
        $this->container['customerBalanceRefunded'] = isset($data['customerBalanceRefunded']) ? $data['customerBalanceRefunded'] : null;
        $this->container['baseCustomerBalanceTotalRefunded'] = isset($data['baseCustomerBalanceTotalRefunded']) ? $data['baseCustomerBalanceTotalRefunded'] : null;
        $this->container['customerBalanceTotalRefunded'] = isset($data['customerBalanceTotalRefunded']) ? $data['customerBalanceTotalRefunded'] : null;
        $this->container['giftCards'] = isset($data['giftCards']) ? $data['giftCards'] : null;
        $this->container['baseGiftCardsAmount'] = isset($data['baseGiftCardsAmount']) ? $data['baseGiftCardsAmount'] : null;
        $this->container['giftCardsAmount'] = isset($data['giftCardsAmount']) ? $data['giftCardsAmount'] : null;
        $this->container['baseGiftCardsInvoiced'] = isset($data['baseGiftCardsInvoiced']) ? $data['baseGiftCardsInvoiced'] : null;
        $this->container['giftCardsInvoiced'] = isset($data['giftCardsInvoiced']) ? $data['giftCardsInvoiced'] : null;
        $this->container['baseGiftCardsRefunded'] = isset($data['baseGiftCardsRefunded']) ? $data['baseGiftCardsRefunded'] : null;
        $this->container['giftCardsRefunded'] = isset($data['giftCardsRefunded']) ? $data['giftCardsRefunded'] : null;
        $this->container['giftMessage'] = isset($data['giftMessage']) ? $data['giftMessage'] : null;
        $this->container['gwId'] = isset($data['gwId']) ? $data['gwId'] : null;
        $this->container['gwAllowGiftReceipt'] = isset($data['gwAllowGiftReceipt']) ? $data['gwAllowGiftReceipt'] : null;
        $this->container['gwAddCard'] = isset($data['gwAddCard']) ? $data['gwAddCard'] : null;
        $this->container['gwBasePrice'] = isset($data['gwBasePrice']) ? $data['gwBasePrice'] : null;
        $this->container['gwPrice'] = isset($data['gwPrice']) ? $data['gwPrice'] : null;
        $this->container['gwItemsBasePrice'] = isset($data['gwItemsBasePrice']) ? $data['gwItemsBasePrice'] : null;
        $this->container['gwItemsPrice'] = isset($data['gwItemsPrice']) ? $data['gwItemsPrice'] : null;
        $this->container['gwCardBasePrice'] = isset($data['gwCardBasePrice']) ? $data['gwCardBasePrice'] : null;
        $this->container['gwCardPrice'] = isset($data['gwCardPrice']) ? $data['gwCardPrice'] : null;
        $this->container['gwBaseTaxAmount'] = isset($data['gwBaseTaxAmount']) ? $data['gwBaseTaxAmount'] : null;
        $this->container['gwTaxAmount'] = isset($data['gwTaxAmount']) ? $data['gwTaxAmount'] : null;
        $this->container['gwItemsBaseTaxAmount'] = isset($data['gwItemsBaseTaxAmount']) ? $data['gwItemsBaseTaxAmount'] : null;
        $this->container['gwItemsTaxAmount'] = isset($data['gwItemsTaxAmount']) ? $data['gwItemsTaxAmount'] : null;
        $this->container['gwCardBaseTaxAmount'] = isset($data['gwCardBaseTaxAmount']) ? $data['gwCardBaseTaxAmount'] : null;
        $this->container['gwCardTaxAmount'] = isset($data['gwCardTaxAmount']) ? $data['gwCardTaxAmount'] : null;
        $this->container['gwBasePriceInclTax'] = isset($data['gwBasePriceInclTax']) ? $data['gwBasePriceInclTax'] : null;
        $this->container['gwPriceInclTax'] = isset($data['gwPriceInclTax']) ? $data['gwPriceInclTax'] : null;
        $this->container['gwItemsBasePriceInclTax'] = isset($data['gwItemsBasePriceInclTax']) ? $data['gwItemsBasePriceInclTax'] : null;
        $this->container['gwItemsPriceInclTax'] = isset($data['gwItemsPriceInclTax']) ? $data['gwItemsPriceInclTax'] : null;
        $this->container['gwCardBasePriceInclTax'] = isset($data['gwCardBasePriceInclTax']) ? $data['gwCardBasePriceInclTax'] : null;
        $this->container['gwCardPriceInclTax'] = isset($data['gwCardPriceInclTax']) ? $data['gwCardPriceInclTax'] : null;
        $this->container['gwBasePriceInvoiced'] = isset($data['gwBasePriceInvoiced']) ? $data['gwBasePriceInvoiced'] : null;
        $this->container['gwPriceInvoiced'] = isset($data['gwPriceInvoiced']) ? $data['gwPriceInvoiced'] : null;
        $this->container['gwItemsBasePriceInvoiced'] = isset($data['gwItemsBasePriceInvoiced']) ? $data['gwItemsBasePriceInvoiced'] : null;
        $this->container['gwItemsPriceInvoiced'] = isset($data['gwItemsPriceInvoiced']) ? $data['gwItemsPriceInvoiced'] : null;
        $this->container['gwCardBasePriceInvoiced'] = isset($data['gwCardBasePriceInvoiced']) ? $data['gwCardBasePriceInvoiced'] : null;
        $this->container['gwCardPriceInvoiced'] = isset($data['gwCardPriceInvoiced']) ? $data['gwCardPriceInvoiced'] : null;
        $this->container['gwBaseTaxAmountInvoiced'] = isset($data['gwBaseTaxAmountInvoiced']) ? $data['gwBaseTaxAmountInvoiced'] : null;
        $this->container['gwTaxAmountInvoiced'] = isset($data['gwTaxAmountInvoiced']) ? $data['gwTaxAmountInvoiced'] : null;
        $this->container['gwItemsBaseTaxInvoiced'] = isset($data['gwItemsBaseTaxInvoiced']) ? $data['gwItemsBaseTaxInvoiced'] : null;
        $this->container['gwItemsTaxInvoiced'] = isset($data['gwItemsTaxInvoiced']) ? $data['gwItemsTaxInvoiced'] : null;
        $this->container['gwCardBaseTaxInvoiced'] = isset($data['gwCardBaseTaxInvoiced']) ? $data['gwCardBaseTaxInvoiced'] : null;
        $this->container['gwCardTaxInvoiced'] = isset($data['gwCardTaxInvoiced']) ? $data['gwCardTaxInvoiced'] : null;
        $this->container['gwBasePriceRefunded'] = isset($data['gwBasePriceRefunded']) ? $data['gwBasePriceRefunded'] : null;
        $this->container['gwPriceRefunded'] = isset($data['gwPriceRefunded']) ? $data['gwPriceRefunded'] : null;
        $this->container['gwItemsBasePriceRefunded'] = isset($data['gwItemsBasePriceRefunded']) ? $data['gwItemsBasePriceRefunded'] : null;
        $this->container['gwItemsPriceRefunded'] = isset($data['gwItemsPriceRefunded']) ? $data['gwItemsPriceRefunded'] : null;
        $this->container['gwCardBasePriceRefunded'] = isset($data['gwCardBasePriceRefunded']) ? $data['gwCardBasePriceRefunded'] : null;
        $this->container['gwCardPriceRefunded'] = isset($data['gwCardPriceRefunded']) ? $data['gwCardPriceRefunded'] : null;
        $this->container['gwBaseTaxAmountRefunded'] = isset($data['gwBaseTaxAmountRefunded']) ? $data['gwBaseTaxAmountRefunded'] : null;
        $this->container['gwTaxAmountRefunded'] = isset($data['gwTaxAmountRefunded']) ? $data['gwTaxAmountRefunded'] : null;
        $this->container['gwItemsBaseTaxRefunded'] = isset($data['gwItemsBaseTaxRefunded']) ? $data['gwItemsBaseTaxRefunded'] : null;
        $this->container['gwItemsTaxRefunded'] = isset($data['gwItemsTaxRefunded']) ? $data['gwItemsTaxRefunded'] : null;
        $this->container['gwCardBaseTaxRefunded'] = isset($data['gwCardBaseTaxRefunded']) ? $data['gwCardBaseTaxRefunded'] : null;
        $this->container['gwCardTaxRefunded'] = isset($data['gwCardTaxRefunded']) ? $data['gwCardTaxRefunded'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets shippingAssignments
     *
     * @return \Krak\MagentoApiClient\Model\SalesDataShippingAssignmentInterface[]
     */
    public function getShippingAssignments()
    {
        return $this->container['shippingAssignments'];
    }

    /**
     * Sets shippingAssignments
     *
     * @param \Krak\MagentoApiClient\Model\SalesDataShippingAssignmentInterface[] $shippingAssignments shippingAssignments
     *
     * @return $this
     */
    public function setShippingAssignments($shippingAssignments)
    {
        $this->container['shippingAssignments'] = $shippingAssignments;

        return $this;
    }

    /**
     * Gets appliedTaxes
     *
     * @return \Krak\MagentoApiClient\Model\TaxDataOrderTaxDetailsAppliedTaxInterface[]
     */
    public function getAppliedTaxes()
    {
        return $this->container['appliedTaxes'];
    }

    /**
     * Sets appliedTaxes
     *
     * @param \Krak\MagentoApiClient\Model\TaxDataOrderTaxDetailsAppliedTaxInterface[] $appliedTaxes appliedTaxes
     *
     * @return $this
     */
    public function setAppliedTaxes($appliedTaxes)
    {
        $this->container['appliedTaxes'] = $appliedTaxes;

        return $this;
    }

    /**
     * Gets itemAppliedTaxes
     *
     * @return \Krak\MagentoApiClient\Model\TaxDataOrderTaxDetailsItemInterface[]
     */
    public function getItemAppliedTaxes()
    {
        return $this->container['itemAppliedTaxes'];
    }

    /**
     * Sets itemAppliedTaxes
     *
     * @param \Krak\MagentoApiClient\Model\TaxDataOrderTaxDetailsItemInterface[] $itemAppliedTaxes itemAppliedTaxes
     *
     * @return $this
     */
    public function setItemAppliedTaxes($itemAppliedTaxes)
    {
        $this->container['itemAppliedTaxes'] = $itemAppliedTaxes;

        return $this;
    }

    /**
     * Gets convertingFromQuote
     *
     * @return bool
     */
    public function getConvertingFromQuote()
    {
        return $this->container['convertingFromQuote'];
    }

    /**
     * Sets convertingFromQuote
     *
     * @param bool $convertingFromQuote convertingFromQuote
     *
     * @return $this
     */
    public function setConvertingFromQuote($convertingFromQuote)
    {
        $this->container['convertingFromQuote'] = $convertingFromQuote;

        return $this;
    }

    /**
     * Gets companyOrderAttributes
     *
     * @return \Krak\MagentoApiClient\Model\CompanyDataCompanyOrderInterface
     */
    public function getCompanyOrderAttributes()
    {
        return $this->container['companyOrderAttributes'];
    }

    /**
     * Sets companyOrderAttributes
     *
     * @param \Krak\MagentoApiClient\Model\CompanyDataCompanyOrderInterface $companyOrderAttributes companyOrderAttributes
     *
     * @return $this
     */
    public function setCompanyOrderAttributes($companyOrderAttributes)
    {
        $this->container['companyOrderAttributes'] = $companyOrderAttributes;

        return $this;
    }

    /**
     * Gets baseCustomerBalanceAmount
     *
     * @return float
     */
    public function getBaseCustomerBalanceAmount()
    {
        return $this->container['baseCustomerBalanceAmount'];
    }

    /**
     * Sets baseCustomerBalanceAmount
     *
     * @param float $baseCustomerBalanceAmount baseCustomerBalanceAmount
     *
     * @return $this
     */
    public function setBaseCustomerBalanceAmount($baseCustomerBalanceAmount)
    {
        $this->container['baseCustomerBalanceAmount'] = $baseCustomerBalanceAmount;

        return $this;
    }

    /**
     * Gets customerBalanceAmount
     *
     * @return float
     */
    public function getCustomerBalanceAmount()
    {
        return $this->container['customerBalanceAmount'];
    }

    /**
     * Sets customerBalanceAmount
     *
     * @param float $customerBalanceAmount customerBalanceAmount
     *
     * @return $this
     */
    public function setCustomerBalanceAmount($customerBalanceAmount)
    {
        $this->container['customerBalanceAmount'] = $customerBalanceAmount;

        return $this;
    }

    /**
     * Gets baseCustomerBalanceInvoiced
     *
     * @return float
     */
    public function getBaseCustomerBalanceInvoiced()
    {
        return $this->container['baseCustomerBalanceInvoiced'];
    }

    /**
     * Sets baseCustomerBalanceInvoiced
     *
     * @param float $baseCustomerBalanceInvoiced baseCustomerBalanceInvoiced
     *
     * @return $this
     */
    public function setBaseCustomerBalanceInvoiced($baseCustomerBalanceInvoiced)
    {
        $this->container['baseCustomerBalanceInvoiced'] = $baseCustomerBalanceInvoiced;

        return $this;
    }

    /**
     * Gets customerBalanceInvoiced
     *
     * @return float
     */
    public function getCustomerBalanceInvoiced()
    {
        return $this->container['customerBalanceInvoiced'];
    }

    /**
     * Sets customerBalanceInvoiced
     *
     * @param float $customerBalanceInvoiced customerBalanceInvoiced
     *
     * @return $this
     */
    public function setCustomerBalanceInvoiced($customerBalanceInvoiced)
    {
        $this->container['customerBalanceInvoiced'] = $customerBalanceInvoiced;

        return $this;
    }

    /**
     * Gets baseCustomerBalanceRefunded
     *
     * @return float
     */
    public function getBaseCustomerBalanceRefunded()
    {
        return $this->container['baseCustomerBalanceRefunded'];
    }

    /**
     * Sets baseCustomerBalanceRefunded
     *
     * @param float $baseCustomerBalanceRefunded baseCustomerBalanceRefunded
     *
     * @return $this
     */
    public function setBaseCustomerBalanceRefunded($baseCustomerBalanceRefunded)
    {
        $this->container['baseCustomerBalanceRefunded'] = $baseCustomerBalanceRefunded;

        return $this;
    }

    /**
     * Gets customerBalanceRefunded
     *
     * @return float
     */
    public function getCustomerBalanceRefunded()
    {
        return $this->container['customerBalanceRefunded'];
    }

    /**
     * Sets customerBalanceRefunded
     *
     * @param float $customerBalanceRefunded customerBalanceRefunded
     *
     * @return $this
     */
    public function setCustomerBalanceRefunded($customerBalanceRefunded)
    {
        $this->container['customerBalanceRefunded'] = $customerBalanceRefunded;

        return $this;
    }

    /**
     * Gets baseCustomerBalanceTotalRefunded
     *
     * @return float
     */
    public function getBaseCustomerBalanceTotalRefunded()
    {
        return $this->container['baseCustomerBalanceTotalRefunded'];
    }

    /**
     * Sets baseCustomerBalanceTotalRefunded
     *
     * @param float $baseCustomerBalanceTotalRefunded baseCustomerBalanceTotalRefunded
     *
     * @return $this
     */
    public function setBaseCustomerBalanceTotalRefunded($baseCustomerBalanceTotalRefunded)
    {
        $this->container['baseCustomerBalanceTotalRefunded'] = $baseCustomerBalanceTotalRefunded;

        return $this;
    }

    /**
     * Gets customerBalanceTotalRefunded
     *
     * @return float
     */
    public function getCustomerBalanceTotalRefunded()
    {
        return $this->container['customerBalanceTotalRefunded'];
    }

    /**
     * Sets customerBalanceTotalRefunded
     *
     * @param float $customerBalanceTotalRefunded customerBalanceTotalRefunded
     *
     * @return $this
     */
    public function setCustomerBalanceTotalRefunded($customerBalanceTotalRefunded)
    {
        $this->container['customerBalanceTotalRefunded'] = $customerBalanceTotalRefunded;

        return $this;
    }

    /**
     * Gets giftCards
     *
     * @return \Krak\MagentoApiClient\Model\GiftCardAccountDataGiftCardInterface[]
     */
    public function getGiftCards()
    {
        return $this->container['giftCards'];
    }

    /**
     * Sets giftCards
     *
     * @param \Krak\MagentoApiClient\Model\GiftCardAccountDataGiftCardInterface[] $giftCards giftCards
     *
     * @return $this
     */
    public function setGiftCards($giftCards)
    {
        $this->container['giftCards'] = $giftCards;

        return $this;
    }

    /**
     * Gets baseGiftCardsAmount
     *
     * @return float
     */
    public function getBaseGiftCardsAmount()
    {
        return $this->container['baseGiftCardsAmount'];
    }

    /**
     * Sets baseGiftCardsAmount
     *
     * @param float $baseGiftCardsAmount baseGiftCardsAmount
     *
     * @return $this
     */
    public function setBaseGiftCardsAmount($baseGiftCardsAmount)
    {
        $this->container['baseGiftCardsAmount'] = $baseGiftCardsAmount;

        return $this;
    }

    /**
     * Gets giftCardsAmount
     *
     * @return float
     */
    public function getGiftCardsAmount()
    {
        return $this->container['giftCardsAmount'];
    }

    /**
     * Sets giftCardsAmount
     *
     * @param float $giftCardsAmount giftCardsAmount
     *
     * @return $this
     */
    public function setGiftCardsAmount($giftCardsAmount)
    {
        $this->container['giftCardsAmount'] = $giftCardsAmount;

        return $this;
    }

    /**
     * Gets baseGiftCardsInvoiced
     *
     * @return float
     */
    public function getBaseGiftCardsInvoiced()
    {
        return $this->container['baseGiftCardsInvoiced'];
    }

    /**
     * Sets baseGiftCardsInvoiced
     *
     * @param float $baseGiftCardsInvoiced baseGiftCardsInvoiced
     *
     * @return $this
     */
    public function setBaseGiftCardsInvoiced($baseGiftCardsInvoiced)
    {
        $this->container['baseGiftCardsInvoiced'] = $baseGiftCardsInvoiced;

        return $this;
    }

    /**
     * Gets giftCardsInvoiced
     *
     * @return float
     */
    public function getGiftCardsInvoiced()
    {
        return $this->container['giftCardsInvoiced'];
    }

    /**
     * Sets giftCardsInvoiced
     *
     * @param float $giftCardsInvoiced giftCardsInvoiced
     *
     * @return $this
     */
    public function setGiftCardsInvoiced($giftCardsInvoiced)
    {
        $this->container['giftCardsInvoiced'] = $giftCardsInvoiced;

        return $this;
    }

    /**
     * Gets baseGiftCardsRefunded
     *
     * @return float
     */
    public function getBaseGiftCardsRefunded()
    {
        return $this->container['baseGiftCardsRefunded'];
    }

    /**
     * Sets baseGiftCardsRefunded
     *
     * @param float $baseGiftCardsRefunded baseGiftCardsRefunded
     *
     * @return $this
     */
    public function setBaseGiftCardsRefunded($baseGiftCardsRefunded)
    {
        $this->container['baseGiftCardsRefunded'] = $baseGiftCardsRefunded;

        return $this;
    }

    /**
     * Gets giftCardsRefunded
     *
     * @return float
     */
    public function getGiftCardsRefunded()
    {
        return $this->container['giftCardsRefunded'];
    }

    /**
     * Sets giftCardsRefunded
     *
     * @param float $giftCardsRefunded giftCardsRefunded
     *
     * @return $this
     */
    public function setGiftCardsRefunded($giftCardsRefunded)
    {
        $this->container['giftCardsRefunded'] = $giftCardsRefunded;

        return $this;
    }

    /**
     * Gets giftMessage
     *
     * @return \Krak\MagentoApiClient\Model\GiftMessageDataMessageInterface
     */
    public function getGiftMessage()
    {
        return $this->container['giftMessage'];
    }

    /**
     * Sets giftMessage
     *
     * @param \Krak\MagentoApiClient\Model\GiftMessageDataMessageInterface $giftMessage giftMessage
     *
     * @return $this
     */
    public function setGiftMessage($giftMessage)
    {
        $this->container['giftMessage'] = $giftMessage;

        return $this;
    }

    /**
     * Gets gwId
     *
     * @return string
     */
    public function getGwId()
    {
        return $this->container['gwId'];
    }

    /**
     * Sets gwId
     *
     * @param string $gwId gwId
     *
     * @return $this
     */
    public function setGwId($gwId)
    {
        $this->container['gwId'] = $gwId;

        return $this;
    }

    /**
     * Gets gwAllowGiftReceipt
     *
     * @return string
     */
    public function getGwAllowGiftReceipt()
    {
        return $this->container['gwAllowGiftReceipt'];
    }

    /**
     * Sets gwAllowGiftReceipt
     *
     * @param string $gwAllowGiftReceipt gwAllowGiftReceipt
     *
     * @return $this
     */
    public function setGwAllowGiftReceipt($gwAllowGiftReceipt)
    {
        $this->container['gwAllowGiftReceipt'] = $gwAllowGiftReceipt;

        return $this;
    }

    /**
     * Gets gwAddCard
     *
     * @return string
     */
    public function getGwAddCard()
    {
        return $this->container['gwAddCard'];
    }

    /**
     * Sets gwAddCard
     *
     * @param string $gwAddCard gwAddCard
     *
     * @return $this
     */
    public function setGwAddCard($gwAddCard)
    {
        $this->container['gwAddCard'] = $gwAddCard;

        return $this;
    }

    /**
     * Gets gwBasePrice
     *
     * @return string
     */
    public function getGwBasePrice()
    {
        return $this->container['gwBasePrice'];
    }

    /**
     * Sets gwBasePrice
     *
     * @param string $gwBasePrice gwBasePrice
     *
     * @return $this
     */
    public function setGwBasePrice($gwBasePrice)
    {
        $this->container['gwBasePrice'] = $gwBasePrice;

        return $this;
    }

    /**
     * Gets gwPrice
     *
     * @return string
     */
    public function getGwPrice()
    {
        return $this->container['gwPrice'];
    }

    /**
     * Sets gwPrice
     *
     * @param string $gwPrice gwPrice
     *
     * @return $this
     */
    public function setGwPrice($gwPrice)
    {
        $this->container['gwPrice'] = $gwPrice;

        return $this;
    }

    /**
     * Gets gwItemsBasePrice
     *
     * @return string
     */
    public function getGwItemsBasePrice()
    {
        return $this->container['gwItemsBasePrice'];
    }

    /**
     * Sets gwItemsBasePrice
     *
     * @param string $gwItemsBasePrice gwItemsBasePrice
     *
     * @return $this
     */
    public function setGwItemsBasePrice($gwItemsBasePrice)
    {
        $this->container['gwItemsBasePrice'] = $gwItemsBasePrice;

        return $this;
    }

    /**
     * Gets gwItemsPrice
     *
     * @return string
     */
    public function getGwItemsPrice()
    {
        return $this->container['gwItemsPrice'];
    }

    /**
     * Sets gwItemsPrice
     *
     * @param string $gwItemsPrice gwItemsPrice
     *
     * @return $this
     */
    public function setGwItemsPrice($gwItemsPrice)
    {
        $this->container['gwItemsPrice'] = $gwItemsPrice;

        return $this;
    }

    /**
     * Gets gwCardBasePrice
     *
     * @return string
     */
    public function getGwCardBasePrice()
    {
        return $this->container['gwCardBasePrice'];
    }

    /**
     * Sets gwCardBasePrice
     *
     * @param string $gwCardBasePrice gwCardBasePrice
     *
     * @return $this
     */
    public function setGwCardBasePrice($gwCardBasePrice)
    {
        $this->container['gwCardBasePrice'] = $gwCardBasePrice;

        return $this;
    }

    /**
     * Gets gwCardPrice
     *
     * @return string
     */
    public function getGwCardPrice()
    {
        return $this->container['gwCardPrice'];
    }

    /**
     * Sets gwCardPrice
     *
     * @param string $gwCardPrice gwCardPrice
     *
     * @return $this
     */
    public function setGwCardPrice($gwCardPrice)
    {
        $this->container['gwCardPrice'] = $gwCardPrice;

        return $this;
    }

    /**
     * Gets gwBaseTaxAmount
     *
     * @return string
     */
    public function getGwBaseTaxAmount()
    {
        return $this->container['gwBaseTaxAmount'];
    }

    /**
     * Sets gwBaseTaxAmount
     *
     * @param string $gwBaseTaxAmount gwBaseTaxAmount
     *
     * @return $this
     */
    public function setGwBaseTaxAmount($gwBaseTaxAmount)
    {
        $this->container['gwBaseTaxAmount'] = $gwBaseTaxAmount;

        return $this;
    }

    /**
     * Gets gwTaxAmount
     *
     * @return string
     */
    public function getGwTaxAmount()
    {
        return $this->container['gwTaxAmount'];
    }

    /**
     * Sets gwTaxAmount
     *
     * @param string $gwTaxAmount gwTaxAmount
     *
     * @return $this
     */
    public function setGwTaxAmount($gwTaxAmount)
    {
        $this->container['gwTaxAmount'] = $gwTaxAmount;

        return $this;
    }

    /**
     * Gets gwItemsBaseTaxAmount
     *
     * @return string
     */
    public function getGwItemsBaseTaxAmount()
    {
        return $this->container['gwItemsBaseTaxAmount'];
    }

    /**
     * Sets gwItemsBaseTaxAmount
     *
     * @param string $gwItemsBaseTaxAmount gwItemsBaseTaxAmount
     *
     * @return $this
     */
    public function setGwItemsBaseTaxAmount($gwItemsBaseTaxAmount)
    {
        $this->container['gwItemsBaseTaxAmount'] = $gwItemsBaseTaxAmount;

        return $this;
    }

    /**
     * Gets gwItemsTaxAmount
     *
     * @return string
     */
    public function getGwItemsTaxAmount()
    {
        return $this->container['gwItemsTaxAmount'];
    }

    /**
     * Sets gwItemsTaxAmount
     *
     * @param string $gwItemsTaxAmount gwItemsTaxAmount
     *
     * @return $this
     */
    public function setGwItemsTaxAmount($gwItemsTaxAmount)
    {
        $this->container['gwItemsTaxAmount'] = $gwItemsTaxAmount;

        return $this;
    }

    /**
     * Gets gwCardBaseTaxAmount
     *
     * @return string
     */
    public function getGwCardBaseTaxAmount()
    {
        return $this->container['gwCardBaseTaxAmount'];
    }

    /**
     * Sets gwCardBaseTaxAmount
     *
     * @param string $gwCardBaseTaxAmount gwCardBaseTaxAmount
     *
     * @return $this
     */
    public function setGwCardBaseTaxAmount($gwCardBaseTaxAmount)
    {
        $this->container['gwCardBaseTaxAmount'] = $gwCardBaseTaxAmount;

        return $this;
    }

    /**
     * Gets gwCardTaxAmount
     *
     * @return string
     */
    public function getGwCardTaxAmount()
    {
        return $this->container['gwCardTaxAmount'];
    }

    /**
     * Sets gwCardTaxAmount
     *
     * @param string $gwCardTaxAmount gwCardTaxAmount
     *
     * @return $this
     */
    public function setGwCardTaxAmount($gwCardTaxAmount)
    {
        $this->container['gwCardTaxAmount'] = $gwCardTaxAmount;

        return $this;
    }

    /**
     * Gets gwBasePriceInclTax
     *
     * @return string
     */
    public function getGwBasePriceInclTax()
    {
        return $this->container['gwBasePriceInclTax'];
    }

    /**
     * Sets gwBasePriceInclTax
     *
     * @param string $gwBasePriceInclTax gwBasePriceInclTax
     *
     * @return $this
     */
    public function setGwBasePriceInclTax($gwBasePriceInclTax)
    {
        $this->container['gwBasePriceInclTax'] = $gwBasePriceInclTax;

        return $this;
    }

    /**
     * Gets gwPriceInclTax
     *
     * @return string
     */
    public function getGwPriceInclTax()
    {
        return $this->container['gwPriceInclTax'];
    }

    /**
     * Sets gwPriceInclTax
     *
     * @param string $gwPriceInclTax gwPriceInclTax
     *
     * @return $this
     */
    public function setGwPriceInclTax($gwPriceInclTax)
    {
        $this->container['gwPriceInclTax'] = $gwPriceInclTax;

        return $this;
    }

    /**
     * Gets gwItemsBasePriceInclTax
     *
     * @return string
     */
    public function getGwItemsBasePriceInclTax()
    {
        return $this->container['gwItemsBasePriceInclTax'];
    }

    /**
     * Sets gwItemsBasePriceInclTax
     *
     * @param string $gwItemsBasePriceInclTax gwItemsBasePriceInclTax
     *
     * @return $this
     */
    public function setGwItemsBasePriceInclTax($gwItemsBasePriceInclTax)
    {
        $this->container['gwItemsBasePriceInclTax'] = $gwItemsBasePriceInclTax;

        return $this;
    }

    /**
     * Gets gwItemsPriceInclTax
     *
     * @return string
     */
    public function getGwItemsPriceInclTax()
    {
        return $this->container['gwItemsPriceInclTax'];
    }

    /**
     * Sets gwItemsPriceInclTax
     *
     * @param string $gwItemsPriceInclTax gwItemsPriceInclTax
     *
     * @return $this
     */
    public function setGwItemsPriceInclTax($gwItemsPriceInclTax)
    {
        $this->container['gwItemsPriceInclTax'] = $gwItemsPriceInclTax;

        return $this;
    }

    /**
     * Gets gwCardBasePriceInclTax
     *
     * @return string
     */
    public function getGwCardBasePriceInclTax()
    {
        return $this->container['gwCardBasePriceInclTax'];
    }

    /**
     * Sets gwCardBasePriceInclTax
     *
     * @param string $gwCardBasePriceInclTax gwCardBasePriceInclTax
     *
     * @return $this
     */
    public function setGwCardBasePriceInclTax($gwCardBasePriceInclTax)
    {
        $this->container['gwCardBasePriceInclTax'] = $gwCardBasePriceInclTax;

        return $this;
    }

    /**
     * Gets gwCardPriceInclTax
     *
     * @return string
     */
    public function getGwCardPriceInclTax()
    {
        return $this->container['gwCardPriceInclTax'];
    }

    /**
     * Sets gwCardPriceInclTax
     *
     * @param string $gwCardPriceInclTax gwCardPriceInclTax
     *
     * @return $this
     */
    public function setGwCardPriceInclTax($gwCardPriceInclTax)
    {
        $this->container['gwCardPriceInclTax'] = $gwCardPriceInclTax;

        return $this;
    }

    /**
     * Gets gwBasePriceInvoiced
     *
     * @return string
     */
    public function getGwBasePriceInvoiced()
    {
        return $this->container['gwBasePriceInvoiced'];
    }

    /**
     * Sets gwBasePriceInvoiced
     *
     * @param string $gwBasePriceInvoiced gwBasePriceInvoiced
     *
     * @return $this
     */
    public function setGwBasePriceInvoiced($gwBasePriceInvoiced)
    {
        $this->container['gwBasePriceInvoiced'] = $gwBasePriceInvoiced;

        return $this;
    }

    /**
     * Gets gwPriceInvoiced
     *
     * @return string
     */
    public function getGwPriceInvoiced()
    {
        return $this->container['gwPriceInvoiced'];
    }

    /**
     * Sets gwPriceInvoiced
     *
     * @param string $gwPriceInvoiced gwPriceInvoiced
     *
     * @return $this
     */
    public function setGwPriceInvoiced($gwPriceInvoiced)
    {
        $this->container['gwPriceInvoiced'] = $gwPriceInvoiced;

        return $this;
    }

    /**
     * Gets gwItemsBasePriceInvoiced
     *
     * @return string
     */
    public function getGwItemsBasePriceInvoiced()
    {
        return $this->container['gwItemsBasePriceInvoiced'];
    }

    /**
     * Sets gwItemsBasePriceInvoiced
     *
     * @param string $gwItemsBasePriceInvoiced gwItemsBasePriceInvoiced
     *
     * @return $this
     */
    public function setGwItemsBasePriceInvoiced($gwItemsBasePriceInvoiced)
    {
        $this->container['gwItemsBasePriceInvoiced'] = $gwItemsBasePriceInvoiced;

        return $this;
    }

    /**
     * Gets gwItemsPriceInvoiced
     *
     * @return string
     */
    public function getGwItemsPriceInvoiced()
    {
        return $this->container['gwItemsPriceInvoiced'];
    }

    /**
     * Sets gwItemsPriceInvoiced
     *
     * @param string $gwItemsPriceInvoiced gwItemsPriceInvoiced
     *
     * @return $this
     */
    public function setGwItemsPriceInvoiced($gwItemsPriceInvoiced)
    {
        $this->container['gwItemsPriceInvoiced'] = $gwItemsPriceInvoiced;

        return $this;
    }

    /**
     * Gets gwCardBasePriceInvoiced
     *
     * @return string
     */
    public function getGwCardBasePriceInvoiced()
    {
        return $this->container['gwCardBasePriceInvoiced'];
    }

    /**
     * Sets gwCardBasePriceInvoiced
     *
     * @param string $gwCardBasePriceInvoiced gwCardBasePriceInvoiced
     *
     * @return $this
     */
    public function setGwCardBasePriceInvoiced($gwCardBasePriceInvoiced)
    {
        $this->container['gwCardBasePriceInvoiced'] = $gwCardBasePriceInvoiced;

        return $this;
    }

    /**
     * Gets gwCardPriceInvoiced
     *
     * @return string
     */
    public function getGwCardPriceInvoiced()
    {
        return $this->container['gwCardPriceInvoiced'];
    }

    /**
     * Sets gwCardPriceInvoiced
     *
     * @param string $gwCardPriceInvoiced gwCardPriceInvoiced
     *
     * @return $this
     */
    public function setGwCardPriceInvoiced($gwCardPriceInvoiced)
    {
        $this->container['gwCardPriceInvoiced'] = $gwCardPriceInvoiced;

        return $this;
    }

    /**
     * Gets gwBaseTaxAmountInvoiced
     *
     * @return string
     */
    public function getGwBaseTaxAmountInvoiced()
    {
        return $this->container['gwBaseTaxAmountInvoiced'];
    }

    /**
     * Sets gwBaseTaxAmountInvoiced
     *
     * @param string $gwBaseTaxAmountInvoiced gwBaseTaxAmountInvoiced
     *
     * @return $this
     */
    public function setGwBaseTaxAmountInvoiced($gwBaseTaxAmountInvoiced)
    {
        $this->container['gwBaseTaxAmountInvoiced'] = $gwBaseTaxAmountInvoiced;

        return $this;
    }

    /**
     * Gets gwTaxAmountInvoiced
     *
     * @return string
     */
    public function getGwTaxAmountInvoiced()
    {
        return $this->container['gwTaxAmountInvoiced'];
    }

    /**
     * Sets gwTaxAmountInvoiced
     *
     * @param string $gwTaxAmountInvoiced gwTaxAmountInvoiced
     *
     * @return $this
     */
    public function setGwTaxAmountInvoiced($gwTaxAmountInvoiced)
    {
        $this->container['gwTaxAmountInvoiced'] = $gwTaxAmountInvoiced;

        return $this;
    }

    /**
     * Gets gwItemsBaseTaxInvoiced
     *
     * @return string
     */
    public function getGwItemsBaseTaxInvoiced()
    {
        return $this->container['gwItemsBaseTaxInvoiced'];
    }

    /**
     * Sets gwItemsBaseTaxInvoiced
     *
     * @param string $gwItemsBaseTaxInvoiced gwItemsBaseTaxInvoiced
     *
     * @return $this
     */
    public function setGwItemsBaseTaxInvoiced($gwItemsBaseTaxInvoiced)
    {
        $this->container['gwItemsBaseTaxInvoiced'] = $gwItemsBaseTaxInvoiced;

        return $this;
    }

    /**
     * Gets gwItemsTaxInvoiced
     *
     * @return string
     */
    public function getGwItemsTaxInvoiced()
    {
        return $this->container['gwItemsTaxInvoiced'];
    }

    /**
     * Sets gwItemsTaxInvoiced
     *
     * @param string $gwItemsTaxInvoiced gwItemsTaxInvoiced
     *
     * @return $this
     */
    public function setGwItemsTaxInvoiced($gwItemsTaxInvoiced)
    {
        $this->container['gwItemsTaxInvoiced'] = $gwItemsTaxInvoiced;

        return $this;
    }

    /**
     * Gets gwCardBaseTaxInvoiced
     *
     * @return string
     */
    public function getGwCardBaseTaxInvoiced()
    {
        return $this->container['gwCardBaseTaxInvoiced'];
    }

    /**
     * Sets gwCardBaseTaxInvoiced
     *
     * @param string $gwCardBaseTaxInvoiced gwCardBaseTaxInvoiced
     *
     * @return $this
     */
    public function setGwCardBaseTaxInvoiced($gwCardBaseTaxInvoiced)
    {
        $this->container['gwCardBaseTaxInvoiced'] = $gwCardBaseTaxInvoiced;

        return $this;
    }

    /**
     * Gets gwCardTaxInvoiced
     *
     * @return string
     */
    public function getGwCardTaxInvoiced()
    {
        return $this->container['gwCardTaxInvoiced'];
    }

    /**
     * Sets gwCardTaxInvoiced
     *
     * @param string $gwCardTaxInvoiced gwCardTaxInvoiced
     *
     * @return $this
     */
    public function setGwCardTaxInvoiced($gwCardTaxInvoiced)
    {
        $this->container['gwCardTaxInvoiced'] = $gwCardTaxInvoiced;

        return $this;
    }

    /**
     * Gets gwBasePriceRefunded
     *
     * @return string
     */
    public function getGwBasePriceRefunded()
    {
        return $this->container['gwBasePriceRefunded'];
    }

    /**
     * Sets gwBasePriceRefunded
     *
     * @param string $gwBasePriceRefunded gwBasePriceRefunded
     *
     * @return $this
     */
    public function setGwBasePriceRefunded($gwBasePriceRefunded)
    {
        $this->container['gwBasePriceRefunded'] = $gwBasePriceRefunded;

        return $this;
    }

    /**
     * Gets gwPriceRefunded
     *
     * @return string
     */
    public function getGwPriceRefunded()
    {
        return $this->container['gwPriceRefunded'];
    }

    /**
     * Sets gwPriceRefunded
     *
     * @param string $gwPriceRefunded gwPriceRefunded
     *
     * @return $this
     */
    public function setGwPriceRefunded($gwPriceRefunded)
    {
        $this->container['gwPriceRefunded'] = $gwPriceRefunded;

        return $this;
    }

    /**
     * Gets gwItemsBasePriceRefunded
     *
     * @return string
     */
    public function getGwItemsBasePriceRefunded()
    {
        return $this->container['gwItemsBasePriceRefunded'];
    }

    /**
     * Sets gwItemsBasePriceRefunded
     *
     * @param string $gwItemsBasePriceRefunded gwItemsBasePriceRefunded
     *
     * @return $this
     */
    public function setGwItemsBasePriceRefunded($gwItemsBasePriceRefunded)
    {
        $this->container['gwItemsBasePriceRefunded'] = $gwItemsBasePriceRefunded;

        return $this;
    }

    /**
     * Gets gwItemsPriceRefunded
     *
     * @return string
     */
    public function getGwItemsPriceRefunded()
    {
        return $this->container['gwItemsPriceRefunded'];
    }

    /**
     * Sets gwItemsPriceRefunded
     *
     * @param string $gwItemsPriceRefunded gwItemsPriceRefunded
     *
     * @return $this
     */
    public function setGwItemsPriceRefunded($gwItemsPriceRefunded)
    {
        $this->container['gwItemsPriceRefunded'] = $gwItemsPriceRefunded;

        return $this;
    }

    /**
     * Gets gwCardBasePriceRefunded
     *
     * @return string
     */
    public function getGwCardBasePriceRefunded()
    {
        return $this->container['gwCardBasePriceRefunded'];
    }

    /**
     * Sets gwCardBasePriceRefunded
     *
     * @param string $gwCardBasePriceRefunded gwCardBasePriceRefunded
     *
     * @return $this
     */
    public function setGwCardBasePriceRefunded($gwCardBasePriceRefunded)
    {
        $this->container['gwCardBasePriceRefunded'] = $gwCardBasePriceRefunded;

        return $this;
    }

    /**
     * Gets gwCardPriceRefunded
     *
     * @return string
     */
    public function getGwCardPriceRefunded()
    {
        return $this->container['gwCardPriceRefunded'];
    }

    /**
     * Sets gwCardPriceRefunded
     *
     * @param string $gwCardPriceRefunded gwCardPriceRefunded
     *
     * @return $this
     */
    public function setGwCardPriceRefunded($gwCardPriceRefunded)
    {
        $this->container['gwCardPriceRefunded'] = $gwCardPriceRefunded;

        return $this;
    }

    /**
     * Gets gwBaseTaxAmountRefunded
     *
     * @return string
     */
    public function getGwBaseTaxAmountRefunded()
    {
        return $this->container['gwBaseTaxAmountRefunded'];
    }

    /**
     * Sets gwBaseTaxAmountRefunded
     *
     * @param string $gwBaseTaxAmountRefunded gwBaseTaxAmountRefunded
     *
     * @return $this
     */
    public function setGwBaseTaxAmountRefunded($gwBaseTaxAmountRefunded)
    {
        $this->container['gwBaseTaxAmountRefunded'] = $gwBaseTaxAmountRefunded;

        return $this;
    }

    /**
     * Gets gwTaxAmountRefunded
     *
     * @return string
     */
    public function getGwTaxAmountRefunded()
    {
        return $this->container['gwTaxAmountRefunded'];
    }

    /**
     * Sets gwTaxAmountRefunded
     *
     * @param string $gwTaxAmountRefunded gwTaxAmountRefunded
     *
     * @return $this
     */
    public function setGwTaxAmountRefunded($gwTaxAmountRefunded)
    {
        $this->container['gwTaxAmountRefunded'] = $gwTaxAmountRefunded;

        return $this;
    }

    /**
     * Gets gwItemsBaseTaxRefunded
     *
     * @return string
     */
    public function getGwItemsBaseTaxRefunded()
    {
        return $this->container['gwItemsBaseTaxRefunded'];
    }

    /**
     * Sets gwItemsBaseTaxRefunded
     *
     * @param string $gwItemsBaseTaxRefunded gwItemsBaseTaxRefunded
     *
     * @return $this
     */
    public function setGwItemsBaseTaxRefunded($gwItemsBaseTaxRefunded)
    {
        $this->container['gwItemsBaseTaxRefunded'] = $gwItemsBaseTaxRefunded;

        return $this;
    }

    /**
     * Gets gwItemsTaxRefunded
     *
     * @return string
     */
    public function getGwItemsTaxRefunded()
    {
        return $this->container['gwItemsTaxRefunded'];
    }

    /**
     * Sets gwItemsTaxRefunded
     *
     * @param string $gwItemsTaxRefunded gwItemsTaxRefunded
     *
     * @return $this
     */
    public function setGwItemsTaxRefunded($gwItemsTaxRefunded)
    {
        $this->container['gwItemsTaxRefunded'] = $gwItemsTaxRefunded;

        return $this;
    }

    /**
     * Gets gwCardBaseTaxRefunded
     *
     * @return string
     */
    public function getGwCardBaseTaxRefunded()
    {
        return $this->container['gwCardBaseTaxRefunded'];
    }

    /**
     * Sets gwCardBaseTaxRefunded
     *
     * @param string $gwCardBaseTaxRefunded gwCardBaseTaxRefunded
     *
     * @return $this
     */
    public function setGwCardBaseTaxRefunded($gwCardBaseTaxRefunded)
    {
        $this->container['gwCardBaseTaxRefunded'] = $gwCardBaseTaxRefunded;

        return $this;
    }

    /**
     * Gets gwCardTaxRefunded
     *
     * @return string
     */
    public function getGwCardTaxRefunded()
    {
        return $this->container['gwCardTaxRefunded'];
    }

    /**
     * Sets gwCardTaxRefunded
     *
     * @param string $gwCardTaxRefunded gwCardTaxRefunded
     *
     * @return $this
     */
    public function setGwCardTaxRefunded($gwCardTaxRefunded)
    {
        $this->container['gwCardTaxRefunded'] = $gwCardTaxRefunded;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


