<?php
/**
 * BundleProductLinkManagementV1AddChildByProductSkuPostBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Krak\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Commerce for B2B
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Krak\MagentoApiClient;

/**
 * BundleProductLinkManagementV1AddChildByProductSkuPostBodyTest Class Doc Comment
 *
 * @category    Class */
// * @description BundleProductLinkManagementV1AddChildByProductSkuPostBody
/**
 * @package     Krak\MagentoApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BundleProductLinkManagementV1AddChildByProductSkuPostBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BundleProductLinkManagementV1AddChildByProductSkuPostBody"
     */
    public function testBundleProductLinkManagementV1AddChildByProductSkuPostBody()
    {
    }

    /**
     * Test attribute "linkedProduct"
     */
    public function testPropertyLinkedProduct()
    {
    }
}
