<?php
/**
 * CatalogDataProductRenderInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Krak\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Commerce for B2B
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Krak\MagentoApiClient;

/**
 * CatalogDataProductRenderInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Represents Data Object which holds enough information to render product This information is put into part as Add To Cart or Add to Compare Data or Price Data
/**
 * @package     Krak\MagentoApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CatalogDataProductRenderInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CatalogDataProductRenderInterface"
     */
    public function testCatalogDataProductRenderInterface()
    {
    }

    /**
     * Test attribute "addToCartButton"
     */
    public function testPropertyAddToCartButton()
    {
    }

    /**
     * Test attribute "addToCompareButton"
     */
    public function testPropertyAddToCompareButton()
    {
    }

    /**
     * Test attribute "priceInfo"
     */
    public function testPropertyPriceInfo()
    {
    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "isSalable"
     */
    public function testPropertyIsSalable()
    {
    }

    /**
     * Test attribute "storeId"
     */
    public function testPropertyStoreId()
    {
    }

    /**
     * Test attribute "currencyCode"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {
    }
}
