<?php
/**
 * CompanyCreditDataHistoryDataInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Krak\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Commerce for B2B
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Krak\MagentoApiClient;

/**
 * CompanyCreditDataHistoryDataInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description History data transfer object interface.
/**
 * @package     Krak\MagentoApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyCreditDataHistoryDataInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CompanyCreditDataHistoryDataInterface"
     */
    public function testCompanyCreditDataHistoryDataInterface()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "companyCreditId"
     */
    public function testPropertyCompanyCreditId()
    {
    }

    /**
     * Test attribute "userId"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "userType"
     */
    public function testPropertyUserType()
    {
    }

    /**
     * Test attribute "currencyCredit"
     */
    public function testPropertyCurrencyCredit()
    {
    }

    /**
     * Test attribute "currencyOperation"
     */
    public function testPropertyCurrencyOperation()
    {
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
    }

    /**
     * Test attribute "rateCredit"
     */
    public function testPropertyRateCredit()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {
    }

    /**
     * Test attribute "creditLimit"
     */
    public function testPropertyCreditLimit()
    {
    }

    /**
     * Test attribute "availableLimit"
     */
    public function testPropertyAvailableLimit()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "datetime"
     */
    public function testPropertyDatetime()
    {
    }

    /**
     * Test attribute "purchaseOrder"
     */
    public function testPropertyPurchaseOrder()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }
}
