<?php
/**
 * CompanyDataCompanyInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Krak\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Commerce for B2B
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Krak\MagentoApiClient;

/**
 * CompanyDataCompanyInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface for Company entity.
/**
 * @package     Krak\MagentoApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyDataCompanyInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CompanyDataCompanyInterface"
     */
    public function testCompanyDataCompanyInterface()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "companyName"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "legalName"
     */
    public function testPropertyLegalName()
    {
    }

    /**
     * Test attribute "companyEmail"
     */
    public function testPropertyCompanyEmail()
    {
    }

    /**
     * Test attribute "vatTaxId"
     */
    public function testPropertyVatTaxId()
    {
    }

    /**
     * Test attribute "resellerId"
     */
    public function testPropertyResellerId()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "countryId"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }

    /**
     * Test attribute "regionId"
     */
    public function testPropertyRegionId()
    {
    }

    /**
     * Test attribute "postcode"
     */
    public function testPropertyPostcode()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "customerGroupId"
     */
    public function testPropertyCustomerGroupId()
    {
    }

    /**
     * Test attribute "salesRepresentativeId"
     */
    public function testPropertySalesRepresentativeId()
    {
    }

    /**
     * Test attribute "rejectReason"
     */
    public function testPropertyRejectReason()
    {
    }

    /**
     * Test attribute "rejectedAt"
     */
    public function testPropertyRejectedAt()
    {
    }

    /**
     * Test attribute "superUserId"
     */
    public function testPropertySuperUserId()
    {
    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {
    }
}
