<?php
/**
 * NegotiableQuoteDataNegotiableQuoteInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Krak\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Commerce for B2B
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Krak\MagentoApiClient;

/**
 * NegotiableQuoteDataNegotiableQuoteInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface NegotiableQuoteInterface
/**
 * @package     Krak\MagentoApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NegotiableQuoteDataNegotiableQuoteInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NegotiableQuoteDataNegotiableQuoteInterface"
     */
    public function testNegotiableQuoteDataNegotiableQuoteInterface()
    {
    }

    /**
     * Test attribute "quoteId"
     */
    public function testPropertyQuoteId()
    {
    }

    /**
     * Test attribute "isRegularQuote"
     */
    public function testPropertyIsRegularQuote()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "negotiatedPriceType"
     */
    public function testPropertyNegotiatedPriceType()
    {
    }

    /**
     * Test attribute "negotiatedPriceValue"
     */
    public function testPropertyNegotiatedPriceValue()
    {
    }

    /**
     * Test attribute "shippingPrice"
     */
    public function testPropertyShippingPrice()
    {
    }

    /**
     * Test attribute "quoteName"
     */
    public function testPropertyQuoteName()
    {
    }

    /**
     * Test attribute "expirationPeriod"
     */
    public function testPropertyExpirationPeriod()
    {
    }

    /**
     * Test attribute "emailNotificationStatus"
     */
    public function testPropertyEmailNotificationStatus()
    {
    }

    /**
     * Test attribute "hasUnconfirmedChanges"
     */
    public function testPropertyHasUnconfirmedChanges()
    {
    }

    /**
     * Test attribute "isShippingTaxChanged"
     */
    public function testPropertyIsShippingTaxChanged()
    {
    }

    /**
     * Test attribute "isCustomerPriceChanged"
     */
    public function testPropertyIsCustomerPriceChanged()
    {
    }

    /**
     * Test attribute "notifications"
     */
    public function testPropertyNotifications()
    {
    }

    /**
     * Test attribute "appliedRuleIds"
     */
    public function testPropertyAppliedRuleIds()
    {
    }

    /**
     * Test attribute "isAddressDraft"
     */
    public function testPropertyIsAddressDraft()
    {
    }

    /**
     * Test attribute "deletedSku"
     */
    public function testPropertyDeletedSku()
    {
    }

    /**
     * Test attribute "creatorId"
     */
    public function testPropertyCreatorId()
    {
    }

    /**
     * Test attribute "creatorType"
     */
    public function testPropertyCreatorType()
    {
    }

    /**
     * Test attribute "originalTotalPrice"
     */
    public function testPropertyOriginalTotalPrice()
    {
    }

    /**
     * Test attribute "baseOriginalTotalPrice"
     */
    public function testPropertyBaseOriginalTotalPrice()
    {
    }

    /**
     * Test attribute "negotiatedTotalPrice"
     */
    public function testPropertyNegotiatedTotalPrice()
    {
    }

    /**
     * Test attribute "baseNegotiatedTotalPrice"
     */
    public function testPropertyBaseNegotiatedTotalPrice()
    {
    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {
    }
}
