<?php
/**
 * CatalogProductRepositoryV1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Krak\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Commerce for B2B
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Krak\MagentoApiClient;

use \Krak\MagentoApiClient\Configuration;
use \Krak\MagentoApiClient\ApiException;
use \Krak\MagentoApiClient\ObjectSerializer;

/**
 * CatalogProductRepositoryV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Krak\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CatalogProductRepositoryV1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for catalogProductRepositoryV1DeleteByIdDelete
     *
     * .
     *
     */
    public function testCatalogProductRepositoryV1DeleteByIdDelete()
    {
    }

    /**
     * Test case for catalogProductRepositoryV1GetGet
     *
     * .
     *
     */
    public function testCatalogProductRepositoryV1GetGet()
    {
    }

    /**
     * Test case for catalogProductRepositoryV1GetListGet
     *
     * .
     *
     */
    public function testCatalogProductRepositoryV1GetListGet()
    {
    }

    /**
     * Test case for catalogProductRepositoryV1SavePost
     *
     * .
     *
     */
    public function testCatalogProductRepositoryV1SavePost()
    {
    }

    /**
     * Test case for catalogProductRepositoryV1SavePut
     *
     * .
     *
     */
    public function testCatalogProductRepositoryV1SavePut()
    {
    }
}
